### PR TITLE
Dockerfiles: Parameterize FROM command, unify Python venv

### LINKED ISSUE #27: Parameterize docker images' `FROM` command
This will enable use to chain/compose the component images into arbitrary ways.  I think it will look like:

```
ARG base_image=exaworks/sdk-base
FROM $base_image
```

The first use-case would be our existing one: creating an image with a single component.  Due to the default argument value, the existing build command will continue to work as-is: `docker build -t rp docker/rp`

The second use-case would be as for pair-wise integrations (two components) or a big monolithic image with all of the components.  We could achieve this by "chaining" the images (e.g., `sdk-base` -> `swift-t` -> `parsl` -> `rp` -> `flux`).

### PR DESCRIPTION
**Pull request by SteVwonder**
Allow the base image to be set at build time for each dockerfile.  This enables the images to be chained/stacked on top of one another. Adjust the CI to leverage this functionality while still testing each component individually.  Opens the door to testing pair-wise integrations.

Closes #27

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
LGTM - thanks!

**Comment by dongahn** [comment]
This has gotten a solid LGTM from @andre-merzky and I will add MWP.

**Comment by SteVwonder** [comment]
@dongahn or @andre-merzky : this will require a manual merge since it modifies the github workflow yaml file (mergify can't merge those changes)

@mergifyio rebase

**Comment by dongahn** [comment]
OK. Pulling this in.

**Pull request merged**
