### PR TITLE
Install Swift/T

### PR DESCRIPTION
**Pull request by j-woz**

### CODE REVIEW

**Comment by j-woz** [comment]
Note that both @hategan and I are trying to install GCC and OpenMPI

**Comment by mtitov** [comment]
@j-woz Justin, did you check it together with Mihael's changes? other option is to have a separate conda-env for swift/t:
```
RUN mamba env create -n swift-t python=3.9 \
 && mamba install -y -n swift-t -c conda-forge \
    gcc zsh openjdk=11 openmpi \
 && mamba install -y -n swift-t -c conda-forge \
    http://web.cels.anl.gov/~woz/swift-t-1.6.0-py39_1.tar.bz2
```

**Comment by j-woz** [comment]
I think it will be fine, we can de-duplicate later.

**Review by mtitov — APPROVED** [review]
LGTM!

Justin, maybe keep installation commands within one `RUN`?
```
RUN mamba install -y -c conda-forge \
    gcc zsh openjdk=11 openmpi \
 && mamba install -y -c conda-forge \
    http://web.cels.anl.gov/~woz/swift-t-1.6.0-py39_1.tar.bz2
```

p.s. @j-woz @hategan seems like it doesn't matter in which order your PRs will be merged (was worried about ordering of packages within docker file, specifically about `gcc` and `gxx_linux-64` packages, but all works fine, and the updated PSI/J tutorial tested)

**Pull request merged**
