### PR TITLE
CI/CD: build all images and deploy base on merge to master

### LINKED ISSUE #24: CI: integrate docker's "build and push" action
It would be good to have the `sdk-base` image continuously deployed via our CI.   This will require creating a secret in the github org and then restructuring the CI yaml a bit: https://docs.docker.com/ci-cd/github-actions/

### PR DESCRIPTION
**Pull request by SteVwonder**
- Add a default `CMD` to swift-t and parsl images as their "sanity check"
- Update the GH workflow that is run on PRs so that all images are built and their "sanity check" is run
- Add a GH workflow that only runs on merge to master that builds and deploys (via a push to docker hub) the base image

Closes #24 

Note that I opted to keep the CI as a single, monolithic job since we plan to merge the dockerfiles anyway, and it is more difficult than I imagined to pass built docker images between GH Action jobs.

### CODE REVIEW

**Comment by SteVwonder** [comment]
Ok.  CI tests finally passed. This is ready for review.

**Comment by dongahn** [comment]
@andre-merzky: I think you should be a major reviewer for this PR.

**Comment by dongahn** [comment]
@andre-merzky: ping.

**Comment by dongahn** [comment]
Please rebase.

**Review by andre-merzky — APPROVED** [review]
Sorry for the delayed response!
This PR looks good to me, thank you!

**Comment by dongahn** [comment]
Thanks @SteVwonder and @andre-merzky !

**Pull request merged**
